'use client';

import Link from 'next/link';
import { ShieldCheck, Car, Clock, Scale, AlertTriangle } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { PageHeader } from '@/components/ui/page-header';
import { usePlatformConfig, describeCancellation } from '@/features/platform/config';

const money = (cents: number) => `$${(cents / 100).toFixed(0)}`;

/**
 * Protection, explained before checkout rather than during it.
 *
 * The tiers and their prices are read from PlatformConfig — the same source the
 * checkout charges from — so this page cannot quote a price the booking flow
 * then contradicts. Cancellation terms are generated by describeCancellation()
 * off the live rules for the same reason.
 */
export default function InsurancePage() {
  const config = usePlatformConfig();
  const tiers = config.data?.protection ?? [];

  return (
    <div className="mx-auto max-w-4xl space-y-8 py-6">
      <PageHeader
        title="Protection & cover"
        description="What is covered, what it costs, and what happens when something goes wrong."
      />

      {/* Tiers — priced from the same config checkout bills against. */}
      <section className="space-y-3">
        <h2 className="display text-xl">Choose your cover at checkout</h2>
        {config.isLoading ? (
          <div className="grid gap-3 sm:grid-cols-3">{[0, 1, 2].map((i) => <Skeleton key={i} className="h-40 w-full" />)}</div>
        ) : (
          <div className="grid gap-3 sm:grid-cols-3">
            {tiers.map((t) => (
              <Card key={t.code} className="flex flex-col">
                <CardContent className="flex flex-1 flex-col py-5">
                  <p className="font-semibold">{t.label}</p>
                  <p className="numeric mt-1 text-2xl font-bold">
                    {t.pricePerDay === 0 ? 'Included' : money(t.pricePerDay)}
                    {t.pricePerDay > 0 && <span className="text-sm font-medium text-muted-foreground">/day</span>}
                  </p>
                  <p className="mt-2 flex-1 text-sm text-muted-foreground">{t.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </section>

      {/* The guarantees that are actually enforced in code. */}
      <section className="space-y-3">
        <h2 className="display text-xl">What we guarantee</h2>
        <div className="grid gap-3 sm:grid-cols-2">
          <Promise
            icon={Car}
            title="A host cancels, you still drive"
            body="If your host cancels, we find you another car for your original dates and cover the price difference up to a set limit. You do not pay more because someone else changed their mind."
          />
          <Promise
            icon={Clock}
            title="A finished trip stays finished"
            body="Damage claims must be opened within a fixed window after the trip ends, with photos. After that the trip is closed and cannot be reopened against you."
          />
          <Promise
            icon={Scale}
            title="Reviews are written blind"
            body="Neither side sees the other's review until both are in or the window closes. A review is an opinion, not a reply to one."
          />
          <Promise
            icon={AlertTriangle}
            title="Citations are passed through, not marked up"
            body="A parking ticket or toll incurred during your trip is charged at cost, evidenced, and only within the window it could have happened in."
          />
        </div>
      </section>

      {/* Cancellation, generated from live rules. */}
      <section className="space-y-3">
        <h2 className="display text-xl">If you need to cancel</h2>
        <Card>
          <CardContent className="divide-y divide-border py-2">
            {config.isLoading ? (
              <div className="space-y-3 py-3">{[0, 1, 2].map((i) => <Skeleton key={i} className="h-10 w-full" />)}</div>
            ) : (
              (['flexible', 'moderate', 'strict'] as const).map((p) => {
                const { title, detail } = describeCancellation(p, config.data);
                return (
                  <div key={p} className="py-3.5">
                    <p className="font-medium">{title}</p>
                    <p className="mt-0.5 text-sm text-muted-foreground">{detail || 'Terms are set per listing.'}</p>
                  </div>
                );
              })
            )}
          </CardContent>
        </Card>
        <p className="text-sm text-muted-foreground">
          Each host picks one of these for their car. The policy that applies to your trip is shown before you pay
          and again on your booking.
        </p>
      </section>

      <Card className="bg-muted/40">
        <CardContent className="flex flex-wrap items-center justify-between gap-3 py-5">
          <div className="flex items-center gap-3">
            <ShieldCheck className="h-6 w-6 shrink-0 text-primary" />
            <p className="text-sm">
              <span className="font-semibold">Something already gone wrong?</span> Open a claim and we will take it
              from there.
            </p>
          </div>
          <Link
            href="/claims"
            className="inline-flex h-10 items-center rounded-lg border border-border bg-card px-4 text-sm font-medium transition-colors hover:bg-muted"
          >
            File a claim
          </Link>
        </CardContent>
      </Card>
    </div>
  );
}

function Promise({
  icon: Icon, title, body,
}: { icon: typeof Car; title: string; body: string }) {
  return (
    <Card>
      <CardContent className="py-5">
        <p className="flex items-center gap-2 font-semibold">
          <Icon className="h-5 w-5 shrink-0 text-primary" /> {title}
        </p>
        <p className="mt-1.5 text-sm text-muted-foreground">{body}</p>
      </CardContent>
    </Card>
  );
}
